description: Liste des produits soumis au taux de TVA de 19%
values:
  '2021-01-01':
    value:
    - abonnement_chaine_cryptee
    - abonnement_chaines_sportives
    - abonnement_dream_box
    - abonnement_pour_autoroute
    - abonnement_prking
    - accessoires
    - accessoires_d_appareils_d_eclairage
    - accessoires_de_beaute
    - accessoires_de_couture_et_broderie
    - accessoires_de_rideaux
    - accessoires_de_toilette
    - accessoires_et_frais_de_reparation_et_d_entretien_d_appareil_de_cuisine
    - accessoires_et_frais_de_reparation_et_d_entretien_d_appareils_electromenagers
    - accessoires_pour_animaux_de_traction
    - accessoires_pour_vehicule
    - achat_alimentation_et_entretien_d_animaux_domestique
    - achat_carte_sim_pour_telephone_portable
    - achat_d_accessoires_d_articles_de_loisirs
    - achat_d_accessoires_de_cyclomoteur
    - achat_d_accessoires_pour_telephone_portable
    - achat_d_appareil_telephone_fixe
    - achat_d_appareil_telephone_portable
    - achat_de_cd_dvd
    - achat_de_jeux_d_echec_de_scrabble_et_autre_jeux_similaires
    - achat_de_laine_de_mousse_ou_de_crin
    - achat_de_laine_pour_couverture
    - achat_de_piece_de_rechange
    - achat_de_terrain_pour_construction_de_logement
    - achat_de_voiture
    - achats_courants_de_fournitures_scolaires_et_frais_de_photocopie_de_documents_scolaires_stylo
    - alcool
    - allocation_touristique
    - allumette
    - amandes_grillees_noix_acajoux
    - ampoule_electrique_tube_neon_starter_electrique
    - appareil_de_chauffage
    - appareil_de_mesure
    - appareil_de_photo
    - appareils_manuels_et_artisanaux_de_broderie_et_de_tissage
    - arachides_grillees
    - armoire_commode_etagere
    - articles_d_hygiene
    - articles_de_bricolage
    - articles_de_jardinage
    - articles_de_sport_de_peche_de_chasse_et_articles_de_plage
    - articles_sanitaires
    - aspirateur_electrique_de_cuisine
    - autre_depense_d_entretien
    - autre_tabac
    - autre_viande_de_dinde
    - autres_accessoires_electriques
    - autres_appareils_d_eclairage
    - autres_appareils_electromenagers
    - autres_articles_de_chauffage_et_de_climatisation_bouillotte_eventail_en
    - autres_articles_de_loisirs
    - autres_articles_et_frais_de_soins_corporels_service_de_toilette_et_sante
    - autres_boissons
    - autres_cafe
    - autres_cereales_transformees
    - autres_charges
    - autres_de_depenses_liees_aux_articles_de_loisirs
    - autres_depenses_liees_aux_combustibles
    - autres_desinfectant
    - autres_frais_de_vacances
    - autres_frais_lies_a_la_ceremonie
    - autres_legumineuses_en_conserve
    - autres_matieres_liees_a_la_peinture_au_badigeonnage_et_d_etancheite
    - autres_mobiliers_complets
    - autres_mobiliers_separes
    - autres_objets_de_decor
    - autres_poissons_en_conserve
    - autres_produits_a_base_d_orge
    - autres_produits_a_base_de_ble_dur
    - autres_produits_a_base_de_ble_tendre
    - autres_produits_d_entretien
    - autres_produits_d_hygiene
    - autres_produits_de_beaute
    - autres_produits_de_maroquinerie
    - autres_produits_en_conserve
    - autres_produits_pharmaceutiques_non_indiques_ailleurs
    - autres_produits_sucres
    - autres_produits_sucres_non_indiques_ailleurs
    - autres_service_d_entretien_des_chaussures_des_tapis_tapisseries
    - autres_services
    - autres_types_de_yaourt
    - autres_ustensiles_de_cuisine
    - bain_douche
    - banc
    - batteur_electrique_yaourtiere_presse_fruits_et_legumes_hachoir_de_viande
    - bavette
    - beignet_souk
    - beurre_animal
    - beurre_vegetale_goldina_jedida
    - bibliotheque
    - biblots
    - biere
    - biere_au_bar
    - biscuit_simple_biscuit_fourre_gaufrettes
    - boisson_energitique
    - boisson_gazeuse
    - boisson_infusion
    - boisson_non_gazeuse_sucre
    - boissons_alcoolisees_sans_indications
    - boissons_alcoolisees_sans_indications_au_bar
    - bonbon
    - borghol
    - bougie
    - bouquets_de_fleurs
    - bsissa
    - buffet_argentiere
    - cafe
    - cafe_nature_melange
    - cafe_nature_pur
    - cafetiere_electrique
    - cake
    - camera_video
    - capre_en_conserve
    - capsule_cafe
    - carburant_pour_vehicule_sans_indications
    - cartable_pour_rentree_scolaire
    - carte_de_recharge_pour_telephone_fixe
    - carte_de_recharge_pour_telephone_portable
    - chaise_chaise_longue
    - chaise_pour_bebe_parc_et_autres_articles
    - chambre_a_coucher
    - champignons_en_conserve
    - charbon_de_bois
    - charges_communes
    - charges_communes_annuelles
    - chauffe_bain_chauffe_eau
    - chauffe_eau
    - chaux
    - chocolat
    - cigarette
    - climatiseur
    - club_de_loisirs
    - cocotte_minute
    - coiffure
    - confiture_et_compote_de_fruits
    - consultation_d_un_voyant
    - couche_adulte
    - couche_bebe
    - couche_periodique
    - couverte_lit_et_couvre_matelas
    - couvertures
    - creme_a_raser
    - creme_chantilly
    - creme_en_poudre_pour_fabrication
    - creme_en_poudre_pour_fabrication_de_glace
    - creme_fraiche
    - creme_legere
    - cuisiniere_a_gaz_ou_electrique_plaque_de_cuisson
    - dentifrice
    - deodorants_encens_et_assimiles
    - depense_annuelle_d_eau_courante_sonede
    - depense_d_eau_achetee
    - depense_d_eau_courante_sonede
    - depense_d_entretien_de_monture_animale
    - depense_d_installation_d_entretien_et_reparation_d_appareils_de_chauffage_et_de_climatisation
    - depense_d_installation_de_branchement_et_d_accessoires_electriques_non_ventilee
    - depense_d_installation_et_de_branchement_electrique
    - depense_de_boiserie
    - depense_de_correspondance
    - depense_de_maconnerie_non_ventilee
    - depense_de_menuiserie_vitrerie_et_de_quincaillerie_non_ventilee
    - depense_de_patisserie_maison_non_ventilees
    - depense_de_peinture_badigeonnage_et_d_etancheite_non_ventilee
    - depense_de_plomberie_et_d_installation_sanitaire
    - depense_de_quincaillerie
    - depense_de_robinetterie_et_d_accessoires_de_plomberie
    - depense_de_transport_pour_voyage_et_vacances_en_tunisie
    - depense_de_vitrerie
    - depense_forfait_pour_telepohone_fixe
    - depense_forfait_pour_telepohone_portable
    - depense_journalier_de_gardiennage_et_de_parking
    - depense_pour_construction_de_logement
    - depense_total_d_entretien_de_moyen_de_transport
    - depenses_alimentaires_exceptionelles_non_ventilees_evenement_familial_fete
    - depenses_de_rentree_scolaire_non_ventilees
    - depenses_de_reparation_et_d_entretien_d_articles_de_loisirs
    - depenses_exceptionnelles_de_transport_non_ventilees
    - detergent
    - drap_et_taie
    - eau_de_cologne_eau_de_toilette_parfum_after_shave
    - eau_de_javel
    - eau_minerale
    - essence_melangee_pour_cyclomoteur
    - essence_pour_vehicule
    - facture_telephone_fixe
    - facture_telephone_portable
    - fauteuil_canape_divan
    - fer_a_repasser
    - fer_forge
    - foureau
    - fourrage_pour_monture_animale
    - frais_d_entretien_et_de_reparation_de_mobilier_complet
    - frais_d_installation_telephone_fixe
    - frais_de_ceremonie_funebre
    - frais_de_chirurgie_esthetique_lifting_liposuccion_et_autres_operations_esthetiques
    - frais_de_location_d_articles_pour_ceremonie_camera_video
    - frais_de_location_de_salle
    - frais_de_parution_d_annonce_et_de_publicite_dans_la_presse
    - frais_de_reparation_non_ventiles
    - frais_de_troupe_musicale_orchestre_troupe_soulamia
    - frais_de_vacances_non_ventiles
    - frais_de_visite_technique
    - frais_journalier_de_peage_autoroute
    - frais_total_de_reparation_de_moyen_de_transport
    - fromage_gervais
    - fromage_rape
    - fromage_sans_indications
    - fromage_type_gruyere
    - fromage_type_nestle
    - fromage_type_rouge
    - gel_douche_apres_shampoing
    - glace_thelja_gervais
    - glaciere
    - graines_de_mais_grille
    - graines_de_tournesol_et_de_courge
    - halkoum
    - halwa_chamia
    - haricot_en_conserve
    - insecticides
    - jebna_frais
    - jeljlan
    - jeux_de_cartes
    - jeux_de_hasard
    - jeux_de_loisirs_dans_les_salles_de_jeux_jeux_de_carte_a_cafe
    - jild
    - jouet_pour_enfant_de_tout_type
    - jus_de_fruits
    - jus_de_legumes
    - kaki_mais_grille_pop_corn
    - ketchup
    - klim_et_margoum
    - knor_poisson
    - knor_viandes
    - knor_volailles
    - lait_aromatise_sterilise
    - lait_caille_en_berlingot
    - lait_concentre_non_sucre
    - lait_concentre_sans_autres_indications
    - lait_concentre_sucre
    - lait_en_poudre_non_sucre
    - lait_en_poudre_sans_autres_indications
    - lait_en_poudre_sucre
    - lait_industrielle_sans_autres_indications
    - lampadaire_lustre_veilleuse_applique_abat_jour
    - landau_et_berceau
    - lavage_et_entretien_de_cyclomoteur
    - lavage_et_repassage
    - lave_linge_seche_linge
    - lave_vaisselle
    - legmi_fermente
    - legmi_fermente_au_bar
    - levure_pour_pain_et_patisserie
    - liqueur
    - lit_pour_bebe
    - lit_sommier
    - location_de_motocyclette
    - location_de_voiture
    - m_hames_industrielle
    - maassel_chicha
    - machine_a_coudre_a_tricoter_a_broder_coffre_fort
    - magnetophone_cassette_video_lecteur_dvd_vcd_lecture_de_disque_compact_chaine_sterio
    - main_d_uvre
    - mais_en_conserve
    - malsouka
    - matelas
    - matieres_premiere_de_maconnerie_et_de_marbririe
    - merguez
    - merguez_chevaline
    - micro_onde_four_electrique
    - mloukhia_en_poudre
    - montant_de_loyer
    - moquette
    - mousse_pour_revetement_du_sol
    - natte
    - nefa
    - nettoyage_a_sec_teinturerie
    - noix_noisettes_pistache_pignon
    - onchoua
    - oreiller_cousins_traversin
    - papier_mouchoir_papier_toilette_lingette
    - papier_peint
    - paquet_de_cigarette
    - parabole
    - patisserie_souk
    - peinture_a_l_eau
    - peinture_a_l_huile
    - peinture_pour_moyen_de_transport
    - petit_lait_en_berlingot
    - petit_lait_frais_de_brebis
    - petit_lait_frais_de_chevre
    - petit_lait_frais_de_vache
    - petit_lait_frais_sans_indications
    - petit_pois_en_conserve
    - piment_frais_en_conserve
    - plantes_medicamenteuses
    - pois_chiche_grille
    - poisons_sales_seches
    - poissons_congeles
    - pots_et_bacs_a_fleurs_ou_plantes_synthetiques
    - poulpe_seche
    - poussette
    - primus_a_petrole_pour_cuisine
    - primus_d_eclairage
    - prise_de_photo_developpement_de_pellicule
    - produit_pour_bebe
    - produits_a_base_d_ufs
    - produits_de_maquillage
    - radio_transistor_radio_reveil
    - recepteur
    - recharge_telephone_fixe
    - recharge_telephone_portable
    - rechaud_electrique_de_cuisine_rechaud_a_gaz
    - refrigerateur_congelateur
    - reparation_de_bijoux
    - reveils_pendule
    - rideaux
    - rigouta
    - saccharine
    - salade_michwia_en_boite
    - salami_de_b_uf
    - salle_a_manger
    - salon
    - sechoir_babilisse
    - service_a_cafe
    - service_a_eau
    - service_d_ustensile_en_metal
    - service_de_table
    - serviette_de_table_nappe
    - shampooing_tfal
    - shwing_gum
    - smen
    - spectacle_sportif
    - sucre_glace
    - sucre_roux
    - sucre_vanille
    - t_ablette
    - table_maida
    - tableau_de_decor
    - tapis
    - televiseur
    - the_infusion
    - the_noir
    - the_verte
    - thon_en_conserve
    - tissus_d_ameublement
    - tomates_seches
    - transfert_en_especes_a_l_interieur_de_pays
    - ustensiles_de_cuisine_en_plastique
    - ustensiles_de_cuisine_sans_specification_de_matiere_premiere
    - ustensiles_en_faience_et_en_porcelaine
    - ustensiles_en_metal
    - ustensiles_en_poterie
    - ustensiles_en_vannerie_en_osier_en_bois_en_peau
    - ustensiles_en_verre
    - valise_sac_mallette_cabas
    - vape_recharge
    - ventilateur
    - viande_hachee_bovine
    - vidange_lavage_et_graissage_de_voiture
    - vin
    - vin_au_bar
    - yaourt_a_boire
    - yaourt_aromatise
    - yaourt_aux_fruits
    - yaourt_creme_dessert
    - yaourt_naturel
    - yaourt_sans_autres_indications
metadata:
  unit: list
documentation: Liste exhaustive des produits et services soumis au taux de TVA de
  19% en Tunisie. Les produits sont identifiés par leur nom de variable OpenFisca.
