description: Liste des produits soumis au taux de TVA de 0%
values:
  '2021-01-01':
    value:
    - abricot
    - achat_d_autre_moyen_de_transport
    - ail_sec
    - ail_verte
    - allocation_pour_omra
    - allocation_pour_pelerinage
    - amande_seche_avec_coque
    - amande_seche_sans_coque
    - amande_verte
    - amidon
    - analgesiques_et_anti_inflammatoires
    - antibiotiques_antibacteriens_et_antimycosiques
    - appareil_acoustique
    - arachide_seche_decortiquee
    - arachide_seche_non_decortiquee
    - argent_de_poche
    - artichaut
    - association_culturelle
    - association_politique
    - association_sportive
    - assurance_auto
    - assurance_de_cyclomoteur
    - aubergine
    - autre_association
    - autre_pain_a_base_de_farine
    - autres
    - autres_agrumes_pamplemousse
    - autres_appareils
    - autres_condiments
    - autres_condiments_verts
    - autres_frais
    - autres_fruits_a_noyaux
    - autres_fruits_a_pepins
    - autres_fruits_non_ventiles_ailleurs
    - autres_fruits_secs
    - autres_graines_et_noix
    - autres_huiles
    - autres_legumes_a_bulbe_et_tubercules
    - autres_legumes_a_feuilles_vertes
    - autres_legumineuses_seches
    - autres_legumineuses_vertes
    - autres_medicaments
    - autres_services_relatifs_aux_produits_alimentaires
    - autres_varietes_de_poissons_frais
    - autres_volailles_et_gibiers
    - avion
    - baguette_de_boulangerie_ou_assimile
    - banane
    - bateau
    - betterave
    - blette
    - bois
    - cahier_et_autres_fournitures_scolaires_pour_rentree_scolaire
    - calamar
    - capres_vert
    - cardon
    - carotte
    - carouia
    - celeri
    - centre_syndicale
    - chameau_vivant
    - chevre_ou_chevreau_vivant
    - choux
    - choux_fleur
    - citron
    - clementine
    - combinaison_pour_bebe
    - concombre
    - consultation_dans_un_etablissement_public
    - courge
    - courgette
    - couscous_industrielle_en_paquet
    - couscous_industrielle_en_vrac
    - crustaces
    - cumin
    - daouara_de_caprin
    - daouara_de_mouton
    - daouara_sans_indications
    - dattes_aligh
    - dattes_communes
    - dattes_degla
    - dattes_vertes
    - daurade
    - depense_de_telegramme
    - depenses_exceptionnelles_de_chirurgie_dentaire_dans_un_etablissement_public
    - dindon_vif
    - dons_en_especes_de_montant_important_a_l_occasion_d_un_evenement_familial_ou_d_une_fete_religieuse
    - dons_importants_et_aumone_sur_les_fonds
    - droit_d_enregistrement
    - droit_et_frais_de_formalites_administratives
    - epinard
    - escalope_de_dinde
    - escargot
    - eufs
    - farine_de_ble_tendre_industrielle_en_paquet
    - farine_de_ble_tendre_industrielle_en_vrac
    - farine_de_sorgho
    - farine_lactee
    - fax_email
    - fenouil
    - feuille_de_fenouil
    - feuilles_de_coriandre
    - feve_seche
    - feve_verte
    - figue
    - figue_de_barbarie
    - figue_seche
    - foie_de_b_uf
    - foie_de_caprin
    - foie_de_chameau
    - foie_de_mouton
    - frais_d_accouchement_dans_un_etablissement_public
    - frais_d_assurance
    - frais_d_autorisation
    - frais_d_ecole_coranique
    - frais_d_entretien_et_de_reparation
    - frais_d_entretien_et_de_reparation_d_autres_biens_durables
    - frais_d_entretien_et_de_reparation_de_mobilier_separes
    - frais_d_entretien_et_de_reparation_des_appareils_de_couture_de_tissage
    - frais_de_couture_de_matelas_en_laine_ou_en_crin
    - frais_de_couture_de_tapisserie_et_d_entretien_d_ameublement
    - frais_de_cuisson_pour_autres_produits_alimentaires
    - frais_de_cuisson_pour_gateau_maison
    - frais_de_cuisson_pour_pain
    - frais_de_filature_et_tissage
    - frais_de_mouture
    - frais_de_radio_scanner_irm_echographie_fibro_dans_un_etablissement_public
    - frais_de_reparation_et_d_entretien_d_appareils_medicaux
    - frais_de_sejour_et_de_traitement_a_l_etranger
    - frais_de_sejour_et_operations_chirurgicales_dans_un_etablissement_public
    - frais_de_tissage_de_tapis_klim_margoum_et_frais_de_pose_de_moquette_et_papier_peint
    - frais_lies_au_culte_et_au_recueillement
    - frais_lies_au_linge_de_maison
    - frais_pour_egorger
    - fraise
    - fruits_de_cueillette
    - fruits_de_mer
    - gombo
    - graine_de_courge_et_de_tournesol
    - grenade
    - gros_pain_de_boulangerie
    - haricot_sec
    - haricot_verte
    - huile_d_olive_emballe
    - huile_d_olive_en_vrac
    - huile_de_friture
    - huile_de_graine_vegetale_subventionne
    - huile_de_mais
    - huile_de_tournesol
    - huiles_melangees
    - instrument_de_musique
    - kenta
    - kharroub
    - korkom
    - lait_de_brebis_frais_ou_caille
    - lait_de_chevre_frais_ou_caille
    - lait_de_vache_frais_ou_caille
    - lait_en_poudre_pour_bebe
    - lait_frais_sans_indications
    - lait_naturel_demi_ecreme_sterilise
    - lait_naturel_ecreme_sterilise
    - lait_naturel_entier_sterilise_exemple
    - lait_naturel_sterilise_sans_indications
    - lait_pasteurise
    - lait_regenere_sterilise
    - lapin
    - lentilles_seches
    - livres_pour_rentree_scolaire
    - loup_de_mer
    - loyer_annuel
    - loyer_effectif
    - loyer_fictif
    - lunettes_de_vue_lentilles_de_contact
    - main_d_oeuvre
    - main_d_uvre_de_maconnerie_et_de_marbrerie
    - main_d_uvre_de_menuiserie
    - main_d_uvre_de_plomberie_et_d_installation_sanitaire
    - main_d_uvre_de_vitrerie
    - main_d_uvre_pour_installation_et_branchement_electrique
    - maquereau
    - medicament_de_maladie_longue_duree
    - melange_de_legumineuses_seches
    - melange_farine_et_semoule
    - melon
    - miel_d_abeille
    - mloukhia_feuilles_vertes
    - mouton_vivant
    - mulet
    - naanaa_sec
    - naanaa_verte
    - navet
    - nefle
    - oignon_sec
    - oignon_verte
    - olives_vertes
    - orange
    - os_de_b_uf
    - pageau
    - pain_a_base_de_semoule
    - pain_a_base_de_son_ble_dur
    - pain_d_orge
    - pain_grille
    - pasteque
    - pate_alimentaire_en_paquet
    - pate_alimentaire_en_vrac
    - peche
    - persil
    - petit_dons_et_charite
    - petit_feve_seche
    - petit_pois_sec
    - petit_pois_vers
    - pignon_pistache_noisette_noix
    - piment_sec_en_gousse
    - poire
    - poireaux
    - pois_chiche_sec
    - pois_chiche_vert
    - poivre
    - pomme
    - poulet_eplume
    - poulet_vif
    - poulpe_frais
    - prune
    - radis
    - raisin_de_table
    - raisin_sec
    - remboursement_annuel
    - remboursement_d_un_pret_logement
    - revues_et_journaux
    - riz_en_grain_en_paquet
    - riz_en_grain_en_vrac
    - rognon_rognon_blanc_cervelle
    - rouget
    - salade_verte
    - sardine
    - sbares
    - seiche
    - semoule_d_orge_en_paquet
    - semoule_d_orge_en_vrac
    - semoule_industrielle
    - semoule_industrielle_en_paquet
    - service_chauffeur
    - service_syndicat
    - services_de_gardiennage_du_logement
    - services_de_jardinage
    - services_de_laboratoire_d_analyses_medicales_et_de_rdiologie_dans_un_etablissement_public
    - services_domestiques
    - soins_dentaires_dans_un_etablissement_public
    - sorgho_en_grain
    - tabel
    - tabel_et_carouia
    - taxe_locative_annuelle
    - taxes_locatives_annuelles
    - taxi
    - tete_et_pattes_de_caprin
    - tete_et_pattes_de_mouton
    - timbre_postal_lettre_recommandee_lettre_express
    - timbres_fiscaux
    - tisane
    - tomates_fraiches
    - transport_maritime
    - tripes_de_b_uf
    - tripes_de_caprin
    - tripes_de_chameau
    - tripes_de_mouton
    - vaccins
    - veau_ou_b_uf_vivant
    - viande_bovine_avec_os
    - viande_bovine_sans_indication
    - viande_bovine_sans_os
    - viande_chevaline
    - viande_d_autruche
    - viande_de_mouton
    - viande_de_porc
    - viande_de_poulet_en_detail
    - viande_de_tete_de_chameau
    - viande_de_tete_et_pattes_de_bovin
    - vignette_et_taxe
    - zaket_el_fitr
    - zgougou
metadata:
  unit: list
documentation: Liste exhaustive des produits et services soumis au taux de TVA de
  0% en Tunisie. Les produits sont identifiés par leur nom de variable OpenFisca (snake_case).
