description: Liste des produits soumis au taux de TVA de 7%
values:
  '2021-01-01':
    value:
    - abonnement_bus
    - abonnement_bus_et_metro
    - abonnement_metro
    - abonnement_moyen_du_transport_prive
    - abonnement_scolaire_bus_et_metro
    - abonnement_scolaire_metro
    - abonnement_scolaire_train
    - abonnement_train
    - achat_carte_internet
    - achat_de_bicyclette
    - achat_de_cyclomoteur_motocyclette
    - ampoule_electrique_economique
    - autre_repas
    - autres_boissons_chaudes
    - autres_frais_d_enseignement
    - autres_frais_d_enseignement_prescolaire
    - autres_frais_d_enseignement_scolaire
    - autres_frais_lies_a_des_services_paramedicaux
    - autres_legumineuses_trempees
    - autres_plats_cuisines_ou_livres_a_domicile
    - autres_spectacles
    - beignet
    - boisson_non_gazeuse_sucree
    - bol_de_sorgho
    - brik
    - bus_autobus_prive
    - bus_autobus_public
    - cafe_prepare
    - car
    - casse_croute_a_la_confiture_beurre_fromage
    - casse_croute_au_thon_a_la_sardine
    - casse_croute_harissa
    - casse_croute_ou_bol_de_lablebi
    - chips_pomme_de_terre_frite
    - cinema
    - consultation_dans_un_clinique_ou_cabinet_prive
    - consultation_de_maladie_longue_duree
    - consultation_sans_indications
    - crepe
    - depense_de_maladie_longue_duree_sans_indication
    - depenses_abonnement_internet
    - depenses_exceptionnelles_de_chirurgie_dentaire_dans_un_etablissement_prive
    - depenses_exceptionnelles_de_chirurgie_dentaire_sans_autre_indication
    - droit_d_entree_aux_monuments_culturels
    - excursion
    - feve_trempee
    - frais_d_accouchement_dans_un_etablissement_prive
    - frais_d_accouchement_irm_sans_autre_indication
    - frais_d_analyse_de_radiologie_et_chimiotherapie
    - frais_d_auto_ecole
    - frais_d_hotel
    - frais_d_infirmerie
    - frais_d_internat
    - frais_de_creche
    - frais_de_formation_en_coiffure
    - frais_de_formation_en_couture
    - frais_de_formation_en_informatique
    - frais_de_jardin_d_enfant
    - frais_de_kinesitherapie_d_orthophonistes
    - frais_de_pension
    - frais_de_publinet
    - frais_de_radio_scanner_irm_echographie_fibro_dans_un_etablissement_prive
    - frais_de_radio_scanner_irm_echographie_fibro_sans_autre_indication
    - frais_de_scolarite
    - frais_de_sejour_et_operations_chirurgicales_dans_un_etablissement_prive
    - frais_de_sejour_et_operations_chirurgicales_sans_autre_indication
    - frais_de_transport_de_bagage_et_de_porte_faix_demenagement
    - frais_garderie_scolaire
    - frais_pour_lecon_particulieres_et_etudes
    - fricasse_pate
    - glace_gervais_thelja
    - hamburger_viande_escalope_poulet_salami
    - haricot_trempe
    - harissa_diari
    - harissa_industrielle
    - imprimante
    - legmi_doux
    - louage_car
    - mais_en_grains
    - metro_bus_metro
    - olive_en_conserve
    - ordinateur_personnel
    - patisserie
    - piment_sec_moulu
    - pizza
    - pizza_a_domicile
    - plat_ou_casse_croute_kaftegi
    - plat_tunisien
    - pois_chiche_moulu
    - pois_chiche_trempe
    - poulet_a_emporter
    - sardine_en_conserve
    - savon_de_menage
    - savon_de_toilette
    - services_de_laboratoire_d_analyses_medicales_et_de_radiologie_dans_un_etablissement_prive
    - services_de_laboratoire_d_analyses_medicales_et_de_radiologie_sans_indication_de_l_etablissement
    - soins_dentaires_dans_un_clinique_ou_cabinet_prive
    - soins_dentaires_sans_autre_indication
    - sucre_cristallise_ou_en_poudre
    - sucre_en_morceau
    - the_et_cafe_prepares_non_ventiles
    - the_prepare
    - theatre
    - tomate_en_conserve_industrielle
    - train
    - transport_rural
    - transport_rural_regulier
    - transport_rural_scolaire_regulier
    - variantes
metadata:
  unit: list
  note: Liste des produits identifiés par leur variable OpenFisca. Cette liste peut
    évoluer dans le temps selon les décisions fiscales.
documentation: Liste exhaustive des produits et services soumis au taux de TVA de
  7% en Tunisie. Les produits sont identifiés par leur nom de variable OpenFisca (snake_case).
